# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieApp' do
pod 'Kingfisher', '~> 5.0'
pod 'YoutubeDirectLinkExtractor'
pod "ExpandableLabel"
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieApp

end
